alias athena_login="ssh athena.dialup.mit.edu -X -l dianah13"
alias 175_login="ssh vlsifarm-03.mit.edu -l dianah13"
alias clang_32asm="clang -m32 -S"
alias compile_analyzer="g++ -std=c++0x example.cpp -o compiled_analyzer"
alias compile_picture_analyzer="g++ -o pictureAnalyzerMain.out pictureAnalyzerMain.cpp -O2 -lm -lpthread -I/usr/X11R6/include -L/usr/X11R6/lib -lm -lpthread"
alias gotogo="cd $GOPATH/src/drartemis"
alias findme="pkg-config --cflags"
alias openstacklogin="ssh 104.130.173.137 -l openstack"
alias raspilogin="ssh drartemis.mit.edu -l pi"
alias uroplogin="ssh dianah13@mightycesar.mit.edu"
alias spacexlogin="ssh root@spacexshouldhire.me"
